2022-02-02 13:55:59,756	WARNING worker.py:1034 -- The agent on node sebastian-VLT-WX0 failed with the following error:
Traceback (most recent call last):
  File "/home/sebastian/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 306, in <module>
    loop.run_until_complete(agent.run())
  File "/home/sebastian/anaconda3/envs/mujoco/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/sebastian/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 131, in run
    modules = self._load_modules()
  File "/home/sebastian/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 81, in _load_modules
    agent_cls_list = dashboard_utils.get_all_modules(
  File "/home/sebastian/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py", line 207, in get_all_modules
    importlib.import_module(name)
  File "/home/sebastian/anaconda3/envs/mujoco/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/sebastian/.local/lib/python3.8/site-packages/ray/new_dashboard/modules/reporter/reporter_head.py", line 15, in <module>
    from ray.autoscaler._private.util import (DEBUG_AUTOSCALING_STATUS,
  File "/home/sebastian/.local/lib/python3.8/site-packages/ray/autoscaler/_private/util.py", line 5, in <module>
    import jsonschema
ModuleNotFoundError: No module named 'jsonschema'
[33m(pid=raylet)[39m Traceback (most recent call last):
[33m(pid=raylet)[39m   File "/home/sebastian/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 317, in <module>
[33m(pid=raylet)[39m     raise e
[33m(pid=raylet)[39m   File "/home/sebastian/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 306, in <module>
[33m(pid=raylet)[39m     loop.run_until_complete(agent.run())
[33m(pid=raylet)[39m   File "/home/sebastian/anaconda3/envs/mujoco/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
[33m(pid=raylet)[39m     return future.result()
[33m(pid=raylet)[39m   File "/home/sebastian/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 131, in run
[33m(pid=raylet)[39m     modules = self._load_modules()
[33m(pid=raylet)[39m   File "/home/sebastian/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 81, in _load_modules
[33m(pid=raylet)[39m     agent_cls_list = dashboard_utils.get_all_modules(
[33m(pid=raylet)[39m   File "/home/sebastian/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py", line 207, in get_all_modules
[33m(pid=raylet)[39m     importlib.import_module(name)
[33m(pid=raylet)[39m   File "/home/sebastian/anaconda3/envs/mujoco/lib/python3.8/importlib/__init__.py", line 127, in import_module
[33m(pid=raylet)[39m     return _bootstrap._gcd_import(name[level:], package, level)
[33m(pid=raylet)[39m   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
[33m(pid=raylet)[39m   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[33m(pid=raylet)[39m   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
[33m(pid=raylet)[39m   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
[33m(pid=raylet)[39m   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
[33m(pid=raylet)[39m   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[33m(pid=raylet)[39m   File "/home/sebastian/.local/lib/python3.8/site-packages/ray/new_dashboard/modules/reporter/reporter_head.py", line 15, in <module>
[33m(pid=raylet)[39m     from ray.autoscaler._private.util import (DEBUG_AUTOSCALING_STATUS,
[33m(pid=raylet)[39m   File "/home/sebastian/.local/lib/python3.8/site-packages/ray/autoscaler/_private/util.py", line 5, in <module>
[33m(pid=raylet)[39m     import jsonschema
[33m(pid=raylet)[39m ModuleNotFoundError: No module named 'jsonschema'